name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.17.1 

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Firebase
      run: |
        npm install -g firebase-tools
        firebase login:ci
        firebase deploy --only hosting --token "$FIREBASE_TOKEN"

      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
